### ISSUE TITLE
Change the default dashboard

### ISSUE THREAD

**Issue by KuenzelIT** [Smashing/smashing#116] opened 2018-08-06 20:55 UTC
Hi,

I feel quite dumb asking this, but why does my default dashboard not change?

I configured it as the documentation says using the default_dashboard configuration:
```ruby
require 'dashing'

configure do
  set :auth_token, 'YOUR_AUTH_TOKEN'
  set :default_dashboard, 'home'

  # See http://www.sinatrarb.com/intro.html > Available Template Languages on
  # how to add additional template languages.
  set :template_languages, %i[html erb]

  helpers do
    def protected!
      # Put any authentication code you want in here.
      # This method is run before accessing any resource.
    end
  end
end

map Sinatra::Application.assets_prefix do
  run Sinatra::Application.sprockets
end

run Sinatra::Application
```

After using `smashing start` again, I still see the `sample.erb` dashboard. My `home` dashboard is in correctly in place.

Does anyone have an idea?

**Comment by kinow** [comment] 2018-08-07 04:31
Hi @KuenzelIT , 

Just tested doing a `smashing new test`, then changing the config.ru line, copied and modified `sample.erb` and saved as `home.erb`. It worked as expected.

Closing as cannot reproduce, but if you need further help, hop in https://gitter.im/Smashing/Lobby, as in the [CONTRIBUTING.md](https://github.com/Smashing/smashing/blob/master/CONTRIBUTING.md) file (there's more info there too).

My env is a Ubuntu 16.04 LTS, with ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu].

Hope that helps.
Bruno

**Closed by kinow** 2018-08-07 04:31 UTC
