### ISSUE TITLE
Tiles Switching

### ISSUE THREAD

**Issue by MartynKeigher** [Smashing/smashing#42] opened 2017-01-06 17:08 UTC
Using this 'tweak' from the dashing days ... 

https://github.com/QubitProducts/dashing-contrib/wiki/Widget:-Switcher

When i add the property to my tile (in my erb file) the tile does not 'switch' more so, it just puts the 2 in the same 'tile area' like so... 

![000029](https://cloud.githubusercontent.com/assets/3298134/21726101/d83a2880-d400-11e6-9a2c-ac6ae0c330ea.jpg)

Here is my code...

```
<script type='text/javascript'>
 $(function() {
// These settings override the defaults set in application.coffee. You can do this on a per dashboardbasis.
//	Dashing.cycleDashboards({stagger: false});
});
</script>

...
...
...

<li data-switcher-interval="3000" data-row="1" data-col="1" data-sizex="1" data-sizey="1">
	<div data-id="onboardingnow" data-view="Hotness" data-title="Agent's Onboarding" data-cool="0" data-warm="15" data-moreinfo="currently"></div>
	<div data-id="srvroffcount" data-view="Hotness" data-title="Servers Offline" data-cool="0" data-warm="1"></div>
	<i class="fa fa-random icon-background"></i>
</li>

```

I believe it has something to do with the absence of `dashing-conrtib` gem, but cannot be 100% sure on that. To see all my code, then my project is here: https://github.com/LabTechGeek/rmm_hud

Thanks,.

-----

_Self-troubleshooting log:_

1. Rolled `jquery.gridster.min.js` to v0.5.1 (from 0.7.0) - did not fix.

**Comment by tylermauthe** [comment] 2017-01-15 17:40
The larger question here is: how can we migrate dashing-contrib. There's a big chunk of very cool, but very custom, code that is tied to Dashing.

I'll see if I can get an example working and provide instructions _if_ I can make it work. I'm going to timebox this effort though, because the more important piece is to understand the problems with integration and to hopefully get all of this code working with `smashing`.

I've reached out to the `dashing-contrib` folks here: https://github.com/QubitProducts/dashing-contrib/issues/40

**Comment by tylermauthe** [comment] 2017-01-15 17:56
Okay, I couldn't actually get this working -- my new Windows laptop doesn't want to play nice with Ruby...

In any case, I took a look at your repo and I'm pretty sure the problem is you haven't correctly installed `dashing-contrib`. Please follow all the instructions here and let me know what happens: https://github.com/QubitProducts/dashing-contrib#installation

**Comment by rmaruszewski** [comment] 2018-01-19 15:10
As a workaround you can just get the Switcher widget from the dashing-contrib project (https://github.com/QubitProducts/dashing-contrib/blob/master/lib/dashing-contrib/assets/widgets/switcher/switcher.coffee) and copy it to the "widgets/switcher" folder of your Smashing project. Should run out of the box.

**Comment by tylermauthe** [comment] 2018-01-20 14:27
Awesome - thanks @rmaruszewski. Closing this.

**Closed by tylermauthe** 2018-01-20 14:27 UTC
