### ISSUE TITLE
ActiveSupport Sinatra Warning

### ISSUE THREAD

**Issue by lhtdesignde** [Smashing/smashing#120] opened 2018-12-26 13:14 UTC
In my newly converted dashboard (from dashing) I'm seeing the following warning:

`WARNING: If you plan to load any of ActiveSupport's core extensions to Hash, be
sure to do so *before* loading Sinatra::Application or Sinatra::Base. If not,
you may disregard this warning.
Set SINATRA_ACTIVESUPPORT_WARNING=false in the environment to hide this warning.`

Can you point me to the file where I can set this variable. I don't think there is any environment file like production or so. I tried to add it in the config.ru, but no luck.

**Comment by lhtdesignde** [comment] 2019-01-30 14:00
Thanks for looking! I'm running it on a raspberry pi as it is. I tried to put it at the really top of of config.ru but I get then:
```
TypeError: no implicit conversion of false into String
  config.ru:1:in `[]='
```
if i put it under the require statement, it doesn't work as in I still get the warning.

**Comment by jrgns** [comment] 2019-02-02 06:36
@lhtdesignde Please post thr first couple of lines of config.ru?

**Comment by kinow** [comment] 2019-02-13 09:45
Do you have any more information like ruby version, smashing version, etc?

On Ubuntu LTS, with ruby 2.5

```
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
```

And using latest smashing, everything works fine, without anything on the terminal.

```bash
$ smashing start
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on 0.0.0.0:3030, CTRL+C to stop
127.0.0.1 - - [13/Feb/2019:22:39:17 +1300] "GET / HTTP/1.1" 302 - 0.0037
127.0.0.1 - - [13/Feb/2019:22:39:17 +1300] "GET /sample HTTP/1.1" 200 2329 0.0264
127.0.0.1 - - [13/Feb/2019:22:39:23 +1300] "GET /views/text.html HTTP/1.1" 200 175 0.0017
127.0.0.1 - - [13/Feb/2019:22:39:23 +1300] "GET /views/meter.html HTTP/1.1" 200 442 0.0005
127.0.0.1 - - [13/Feb/2019:22:39:23 +1300] "GET /views/list.html HTTP/1.1" 200 493 0.0005
127.0.0.1 - - [13/Feb/2019:22:39:23 +1300] "GET /views/number.html HTTP/1.1" 200 343 0.0005
127.0.0.1 - - [13/Feb/2019:22:39:23 +1300] "GET /views/graph.html HTTP/1.1" 200 183 0.0005
127.0.0.1 - - [13/Feb/2019:22:39:23 +1300] "GET /public/favicon.ico HTTP/1.1" 404 683 0.0006
127.0.0.1 - - [13/Feb/2019:22:40:09 +1300] "GET /events HTTP/1.1" 200 - 45.5435
127.0.0.1 - - [13/Feb/2019:22:40:21 +1300] "GET /events HTTP/1.1" 200 - 3.5811
127.0.0.1 - - [13/Feb/2019:22:40:31 +1300] "GET /events HTTP/1.1" 200 - 6.8965
^CExiting...
```

But if one of us could reproduce it, fixing it shouldn't be very hard.

Cheers

**Comment by lhtdesignde** [comment] 2019-02-16 12:58
Hi! Thanks for the help and sorry for the delayed response. My current config.ru:

```
require 'dashing'

configure do
  set :auth_token, 'YOUR_AUTH_TOKEN'
  set :default_dashboard, 'engineering'

  # See http://www.sinatrarb.com/intro.html > Available Template Languages on
  # how to add additional template languages.
  set :template_languages, %i[html erb]

  helpers do
    def protected!
      # Put any authentication code you want in here.
      # This method is run before accessing any resource.
    end
  end
end

map Sinatra::Application.assets_prefix do
  run Sinatra::Application.sprockets
end

run Sinatra::Application
```

**Comment by lhtdesignde** [comment] 2019-02-16 13:05
i'm seeing this on multiple computers, not just on the raspberry. e.g. on my macbook version 10.14.3.
here i'm running "ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-darwin18]" with smashing version 1.1.0

**Comment by jrgns** [comment] 2019-02-19 19:36
@lhtdesignde I can't reproduce it this side either, using the exact version you have. I'm guessing there's left over code from your dashing project that's causing it. Maybe try starting with a fresh smashing dashboard, and adding small pieces of code until the error comes back?

**Comment by kinow** [comment] 2021-05-04 03:48
We were not able to reproduce it. Users with similar issue should be able to re-open or open a new issue :+1: closing for now (but really feel free to re-open if anyone is able to reproduce, perhaps in a Ubuntu LTS/arch/centos latest/etc distro, which can be tested if one of the devs use the env, or via Docker?)

Thanks!

**Closed by kinow** 2021-05-04 03:48 UTC

**Comment by lhtdesignde** [comment] 2021-05-05 11:41
i still see this but at the end it's just a warning. Thanks for looking into it!
